-- Create USERS table
CREATE TABLE IF NOT EXISTS newusers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create PRODUCTS table
CREATE TABLE IF NOT EXISTS products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    image_url VARCHAR(255)
);

-- Create ORDERS table
CREATE TABLE newusers (
  id INT NOT NULL AUTO_INCREMENT,
  fullName VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  address VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Example INSERT Products (Add all 100 products here)
INSERT INTO products (name, description, price, stock, image_url) VALUES
('Fresh Apples', 'Fresh and juicy apples.', 1.99, 50, 'images/apple.jpg'),
('Organic Milk', 'Pure organic milk.', 2.49, 40, 'images/milk.jpg'),
('Whole Wheat Bread', 'Healthy whole wheat bread.', 1.29, 60, 'images/bread.jpg'),
('Bananas', 'Fresh yellow bananas.', 0.99, 70, 'images/bananas.jpg'),
('Tomatoes', 'Red ripe tomatoes.', 1.79, 65, 'images/tomatoes.jpg'),
('Carrots', 'Crunchy fresh carrots.', 1.49, 55, 'images/carrots.jpg'),
('Eggs (12 Pack)', 'Pack of 12 fresh eggs.', 3.99, 30, 'images/eggs.jpg'),
('Cheese', 'Delicious cheese.', 4.99, 25, 'images/cheese.jpg'),
('Potatoes', 'Farm fresh potatoes.', 0.89, 80, 'images/potatoes.jpg'),
('Rice (5kg)', 'Premium quality rice.', 9.99, 40, 'images/rice.jpg'),
('Chicken Breast', 'Fresh chicken breast.', 5.99, 35, 'images/chicken.jpg'),
('Orange Juice', 'Natural orange juice.', 3.49, 45, 'images/orange-juice.jpg'),
('Strawberries', 'Sweet strawberries.', 3.99, 30, 'images/strawberries.jpg'),
('Olive Oil', 'Pure olive oil.', 6.99, 20, 'images/olive-oil.jpg'),
('Peanut Butter', 'Creamy peanut butter.', 2.99, 50, 'images/peanut-butter.jpg'),
('Yogurt', 'Fresh dairy yogurt.', 2.49, 60, 'images/yogurt.jpg'),
('Green Peppers', 'Fresh green peppers.', 1.79, 40, 'images/peppers.jpg'),
('Almonds', 'Nutritious almonds.', 7.99, 20, 'images/almonds.jpg'),
('Mangoes', 'Sweet ripe mangoes.', 2.99, 35, 'images/mangoes.jpg'),
('Honey', 'Natural organic honey.', 5.49, 25, 'images/honey.jpg'),
('Watermelon', 'Big juicy watermelon.', 4.49, 15, 'images/watermelon.jpg'),
('Lemon', 'Fresh lemons.', 1.59, 50, 'images/lemon.jpg'),
('Cucumber', 'Cool cucumbers.', 1.29, 50, 'images/cucumber.jpg'),
('Garlic', 'Fresh garlic bulbs.', 2.19, 40, 'images/garlic.jpg'),
('Pineapple', 'Tropical pineapple.', 3.89, 20, 'images/pineapple.jpg'),
('Avocados', 'Creamy avocados.', 1.99, 30, 'images/avocado.jpg'),
('Peaches', 'Sweet juicy peaches.', 2.69, 25, 'images/peaches.jpg'),
('Spinach', 'Fresh green spinach.', 1.39, 50, 'images/spinach.jpg'),
('Zucchini', 'Green zucchinis.', 1.49, 40, 'images/zucchini.jpg'),
('Cabbage', 'Healthy cabbage.', 2.29, 30, 'images/cabbage.jpg'),
('Broccoli', 'Green broccoli.', 2.19, 45, 'images/broccoli.jpg'),
('Lettuce', 'Fresh lettuce.', 1.19, 60, 'images/lettuce.jpg'),
('Iceberg Lettuce', 'Crisp iceberg lettuce.', 1.49, 55, 'images/iceberg-lettuce.jpg'),
('Cherries', 'Sweet red cherries.', 4.99, 20, 'images/cherries.jpg'),
('Pears', 'Juicy pears.', 2.99, 35, 'images/pears.jpg'),
('Cantaloupe', 'Refreshing cantaloupe.', 3.69, 25, 'images/cantaloupe.jpg'),
('Raspberries', 'Fresh raspberries.', 5.99, 15, 'images/raspberries.jpg'),
('Blackberries', 'Sweet blackberries.', 5.49, 15, 'images/blackberries.jpg'),
('Blueberries', 'Healthy blueberries.', 6.99, 20, 'images/blueberries.jpg'),
('Grapes', 'Fresh grapes.', 3.49, 30, 'images/grapes.jpg'),
('Strawberry Jam', 'Sweet strawberry jam.', 3.99, 30, 'images/strawberry-jam.jpg'),
('Apple Cider Vinegar', 'Healthy vinegar.', 2.79, 25, 'images/apple-cider-vinegar.jpg'),
('Corn', 'Sweet corn.', 1.59, 50, 'images/corn.jpg'),
('Frozen Peas', 'Frozen green peas.', 2.49, 40, 'images/frozen-peas.jpg'),
('Frozen Spinach', 'Frozen spinach.', 2.79, 35, 'images/frozen-spinach.jpg'),
('Frozen Broccoli', 'Frozen broccoli.', 3.19, 30, 'images/frozen-broccoli.jpg'),
('Frozen Mixed Vegetables', 'Frozen vegetable mix.', 2.99, 25, 'images/frozen-mixed-vegetables.jpg'),
('Frozen Fries', 'Frozen French fries.', 3.49, 40, 'images/frozen-fries.jpg'),
('Frozen Pizza', 'Delicious frozen pizza.', 4.99, 30, 'images/frozen-pizza.jpg'),
('Bagels', 'Fresh bagels.', 2.69, 50, 'images/bagels.jpg'),
('Croissants', 'Buttery croissants.', 3.29, 40, 'images/croissants.jpg'),
('English Muffins', 'English style muffins.', 2.99, 45, 'images/english-muffins.jpg'),
('Donuts', 'Sweet donuts.', 1.89, 60, 'images/donuts.jpg'),
('Muffins', 'Tasty muffins.', 2.49, 55, 'images/muffins.jpg'),
('Brownies', 'Chocolate brownies.', 3.99, 30, 'images/brownies.jpg'),
('Cookies', 'Delicious cookies.', 2.99, 50, 'images/cookies.jpg'),
('Ice Cream', 'Creamy ice cream.', 4.49, 25, 'images/ice-cream.jpg'),
('Chocolate', 'Rich chocolate.', 2.69, 40, 'images/chocolate.jpg'),
('Gum', 'Chewing gum.', 1.29, 80, 'images/gum.jpg'),
('Candy Bars', 'Sweet candy bars.', 1.49, 70, 'images/candy-bars.jpg'),
('Popcorn', 'Buttery popcorn.', 2.29, 45, 'images/popcorn.jpg'),
('Potato Chips', 'Crispy potato chips.', 1.79, 60, 'images/potato-chips.jpg'),
('Tortilla Chips', 'Crunchy tortilla chips.', 2.49, 55, 'images/tortilla-chips.jpg'),
('Pretzels', 'Salty pretzels.', 1.99, 50, 'images/pretzels.jpg'),
('Nacho Cheese', 'Spicy nacho cheese.', 2.29, 30, 'images/nacho-cheese.jpg'),
('Mustard', 'Classic mustard.', 1.49, 50, 'images/mustard.jpg'),
('Ketchup', 'Tomato ketchup.', 1.69, 60, 'images/ketchup.jpg'),
('Hot Sauce', 'Hot spicy sauce.', 2.29, 40, 'images/hot-sauce.jpg'),
('BBQ Sauce', 'Barbecue sauce.', 2.79, 35, 'images/bbq-sauce.jpg'),
('Soy Sauce', 'Authentic soy sauce.', 1.99, 50, 'images/soy-sauce.jpg'),
('Vinegar', 'Cooking vinegar.', 1.49, 55, 'images/vinegar.jpg'),
('Mayonnaise', 'Creamy mayonnaise.', 2.99, 30, 'images/mayonnaise.jpg'),
('Salsa', 'Fresh salsa.', 2.49, 40, 'images/salsa.jpg'),
('Guacamole', 'Avocado guacamole.', 3.69, 25, 'images/guacamole.jpg'),
('Ranch Dressing', 'Ranch dressing.', 2.19, 30, 'images/ranch-dressing.jpg'),
('Olives', 'Green olives.', 2.99, 35, 'images/olives.jpg'),
('Pickles', 'Sour pickles.', 1.89, 45, 'images/pickles.jpg'),
('Canned Tomatoes', 'Canned tomatoes.', 1.79, 50, 'images/canned-tomatoes.jpg'),
('Canned Beans', 'Canned beans.', 1.49, 50, 'images/canned-beans.jpg'),
('Canned Corn', 'Canned sweet corn.', 1.39, 50, 'images/canned-corn.jpg'),
('Canned Peas', 'Canned peas.', 1.29, 50, 'images/canned-peas.jpg'),
('Canned Tuna', 'Canned tuna.', 2.19, 40, 'images/canned-tuna.jpg'),
('Canned Chicken', 'Canned chicken.', 3.29, 30, 'images/canned-chicken.jpg'),
('Canned Soup', 'Ready soup.', 2.49, 35, 'images/canned-soup.jpg'),
('Beef Stew', 'Ready beef stew.', 3.99, 25, 'images/beef-stew.jpg'),
('Canned Chili', 'Canned chili.', 2.99, 30, 'images/canned-chili.jpg'),
('Boxed Mac & Cheese', 'Mac & Cheese.', 1.49, 50, 'images/boxed-mac-cheese.jpg'),
('Instant Noodles', 'Instant noodles.', 0.99, 70, 'images/instant-noodles.jpg'),
('Rice Pilaf', 'Rice pilaf.', 2.69, 35, 'images/rice-pilaf.jpg'),
('Pasta', 'Delicious pasta.', 1.49, 60, 'images/pasta.jpg'),
('Spaghetti Sauce', 'Spaghetti sauce.', 2.79, 30, 'images/spaghetti-sauce.jpg'),
('Lasagna', 'Frozen lasagna.', 4.99, 25, 'images/lasagna.jpg'),
('Tacos', 'Mexican tacos.', 3.29, 40, 'images/tacos.jpg'),
('Fajita Mix', 'Fajita seasoning.', 2.49, 30, 'images/fajita-mix.jpg'),
('Pizza Dough', 'Ready pizza dough.', 2.29, 30, 'images/pizza-dough.jpg'),
('Tortillas', 'Soft tortillas.', 2.99, 50, 'images/tortillas.jpg'),
('Pita Bread', 'Fresh pita bread.', 2.19, 40, 'images/pita-bread.jpg'),
('Bagged Salad', 'Mixed salad.', 3.49, 30, 'images/bagged-salad.jpg'),
('Frozen Vegetables', 'Frozen vegetable bag.', 1.99, 40, 'images/frozen-vegetables.jpg'),
('Canned Fruit', 'Canned mixed fruit.', 2.29, 30, 'images/canned-fruit.jpg');
